### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by liuyongliu2000** [SHI-Labs/Versatile-Diffusion#6]
Traceback (most recent call last):
  File "C:\Versatile-Diffusion-master\main.py", line 19, in <module>
    cfg = get_command_line_args()
  File "C:\Versatile-Diffusion-master\lib\cfg_helper.py", line 382, in get_command_line_args
    cfg = load_cfg_yaml(args.config)
  File "C:\Versatile-Diffusion-master\lib\cfg_helper.py", line 301, in load_cfg_yaml
    if osp.isfile(path):
  File "C:\Softwares\anaconda3\envs\versatile-diffusion\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by xingqian2018** [comment]
This error occurs when you type the config name wrong; in other words, somehow, the config/experiment/ does not contain the target config you would like to execute. Please double-check the config name.
